coverage:
  status:
    project:
      default:
        target: 65%
        threshold: 0%
    patch: off
ignore:
  - "src/main/java/com/karankumar/bookproject/BookProjectApplication.java"
  - "**/*.md"
